### ISSUE TITLE
No steam - No Support? || Bad show no steam player

### ISSUE THREAD

**Issue by BlackYuzia** [boomix/BoomPanel#3]
@boomix hi (again :D)
Now I full install **BoomPanel** and I get some ... some shit?
If in my server play **NO STEAM** player, I get broken **STEAMID** and **IP**
It's can be fix? (and If player not found in STEAM DataBase player, pls give him avatar: "No Steam".
and he's real nick names.
Screenshot:
![2017-12-04_150417](https://user-images.githubusercontent.com/25010528/33554333-ec1d7686-d904-11e7-9dac-8eed5c562d72.png)

**Comment by boomix** [comment]
Try to run this query in your database and then check if you still get the problem.
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

**Comment by BlackYuzia** [comment]
@boomix I try tihs but I get:

```
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))
Ответ MySQL: Документация

#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation 
```

**Comment by BlackYuzia** [comment]
when I delete **GLOBAL**

` SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))`
query go.

**Comment by BlackYuzia** [comment]
I test now, and No.
That **did't** help.

**Comment by shavitush** [comment]
It's just `GetClientAuthId` returning wrong IDs for non-Steam players. It's a SourceMod "issue" and you won't get any help from the devs.

**Comment by boomix** [comment]
It isnt really that the server returning wrong IDs, it returns clientID from database ( I do hope you have steam`ed server :D ). Everything seems to work there fine, except that you need to ask your hosting or someone who has root access so that they execute my given command in SQL so it works fine for you.

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

When that will be set, it should work just fine.
Rewriting queries to make it work with ONLY_FULL_GROUP_BY could be quite hard, not even sure if thats really possible without making multiple queries, but I want to keep the load speed for the panel good.
